# Generated by Django 4.1.3 on 2022-12-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='SKU',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
